language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
install:
  - pip install -r requirements.txt
  - pip install pycodestyle

stages:
  - pycodestyle_py2
  - pycodestyle_py3
  - test_py2
  - test_py3

jobs:
  include:
    - stage: pycodestyle_py2
      python: 2.7
      script: pycodestyle --show-pep8 $(find . -name "*.py") || exit 0
    - stage: pycodestyle_py3
      python: 3.8
      script: pycodestyle --show-pep8 $(find . -name "*.py") || exit 0
    - stage: test_py2
      python:
      - "2.7"
      - "pypy"
      script: python setup.py test
    - stage: test_py3
      python:
      - "3.8"
      - "pypy3"
      script: python setup.py test
