language: python
os: linux
dist: xenial

python:
  - "2.7"
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage
install:
  - pip install -r requirements.txt
script:
  - coverage run setup.py test
  - coverage report -m
