language: python
os: linux
dist: xenial

python:
  - "2.7"
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage
install:
  - pip install -r requirements.txt
script:
  - echo "service_name: ${service_name}" > .coveralls.yml
  - echo "repo_token: ${repo_token}" >> .coveralls.yml
  - coverage run setup.py test
  - coverage report -m
