language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
before_script:
  - "pycodestyle ."
script:
  - python setup.py test
